In [2]:
import pandas as pd
from functools import reduce

orders_dataset = pd.read_csv("files/olist_orders_dataset.csv")
order_items_dataset = pd.read_csv("files/olist_order_items_dataset.csv")
order_review_dataset = pd.read_csv('files/olist_order_reviews_dataset.csv')
order_payments_dataset = pd.read_csv('files/olist_order_payments_dataset.csv')
order_products_dataset = pd.read_csv('files/olist_products_dataset.csv')
order_sellers_dataset = pd.read_csv('files/olist_sellers_dataset.csv')
order_customer_dataset = pd.read_csv('files/olist_customers_dataset.csv')
order_geolocation_dataset = pd.read_csv('files/olist_geolocation_dataset.csv')

dfs = [
    orders_dataset,
    order_items_dataset,
    order_payments_dataset,
    order_review_dataset
]

merged_df = reduce(lambda left, right: pd.merge(left, right, on="order_id", how="inner"), dfs)

In [3]:
merged_df = pd.merge(merged_df, order_products_dataset, on="product_id", how="left")
merged_df = pd.merge(merged_df, order_sellers_dataset, right_on="seller_id", left_on="seller_id",how="left")
merged_df = pd.merge(merged_df, order_customer_dataset, on="customer_id", how="left")

In [ ]:
merged_df.columns
merged_df.

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'review_id', 'review_score',
       'review_comment_title', 'review_comment_message',
       'review_creation_date', 'review_answer_timestamp',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'geolocation_zip_code_prefix', 'geolocation_lat',
       'geolocation_lng'],
      dtype='object')

In [ ]:
geo = (
    order_geolocation_dataset
    .groupby("geolocation_zip_code_prefix", as_index=False)
    .agg({
        "geolocation_lat": "mean",
        "geolocation_lng": "mean"
    })
)

merged_df = merged_df.merge(geo, left_on="customer_zip_code_prefix", right_on="geolocation_zip_code_prefix", how="left")

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
0                             1001       -23.550190       -46.634024
1                             1002       -23.548146       -46.634979
2                             1003       -23.548994       -46.635731
3                             1004       -23.549799       -46.634757
4                             1005       -23.549456       -46.636733
...                            ...              ...              ...
19010                        99960       -27.953722       -52.025511
19011                        99965       -28.183372       -52.039850
19012                        99970       -28.343766       -51.874689
19013                        99980       -28.389129       -51.843836
19014                        99990       -28.329595       -51.769362

[19015 rows x 3 columns]

In [1]:
import pandas as pd
from functools import reduce

In [2]:
orders_dataset = pd.read_csv("files/olist_orders_dataset.csv")
orders_dataset.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [ ]:
order_items_dataset = pd.read_csv("files/olist_order_items_dataset.csv")
order_items_dataset.head()

In [ ]:
print(type(orders_dataset))
print(type(order_items_dataset))

In [ ]:
# orders_dataset , order_items_dataset

data = pd.merge(orders_dataset, order_items_dataset, on='order_id', how = "inner")
data.head()
# print(data[data['order_id'] == '00018f77f2f0320c557190d7a144bdd3'])

In [ ]:
order_review_dataset = pd.read_csv('files/olist_order_reviews_dataset.csv')
order_review_dataset

In [ ]:
order_payments_dataset = pd.read_csv('files/olist_order_payments_dataset.csv')
order_payments_dataset

In [ ]:
dfs = [
    orders_dataset,
    order_items_dataset,
    order_payments_dataset,
    order_review_dataset
]

merged_df = reduce(lambda left, right: pd.merge(left, right, on="order_id", how="inner"), dfs)

merged_df.head()

In [ ]:
order_products_dataset = pd.read_csv('files/olist_products_dataset.csv')
order_products_dataset

In [ ]:
order_sellers_dataset = pd.read_csv('files/olist_sellers_dataset.csv')
order_sellers_dataset

In [ ]:
order_customer_dataset = pd.read_csv('files/olist_customers_dataset.csv')
order_customer_dataset

In [ ]:
order_geolocation_dataset = pd.read_csv('files/olist_geolocation_dataset.csv')
order_geolocation_dataset

In [ ]:
merged_df = pd.merge(merged_df, order_products_dataset, on="product_id", how="left")

In [ ]:
merged_df = pd.merge(merged_df, order_sellers_dataset, on="seller_id", how="left")
merged_df.head()

In [ ]:
merged_df = pd.merge(
    merged_df,
    order_geolocation_dataset,
    left_on="seller_zip_code_prefix",
    right_on="geolocation_zip_code_prefix",
    how="left"
)
merged_df.head()

In [ ]:

merged_df = pd.merge(merged_df, order_customer_dataset, on="customer_id", how="left")
merged_df.head()

In [ ]:
merged_df.isnull().sum()

In [10]:
merged_df.loc[
    merged_df["order_delivered_customer_date"].isna(),
    "order_status"
].value_counts()

order_status
shipped        1167
canceled        546
invoiced        370
processing      370
unavailable       7
approved          3
Name: count, dtype: int64

In [9]:
merged_df.loc[
    merged_df["order_delivered_carrier_date"].isna(),
    "order_status"
].value_counts()

order_status
canceled       483
invoiced       370
processing     370
unavailable      7
approved         3
Name: count, dtype: int64

In [ ]:
merged_df[merged_df["product_category_name"].isna()]

In [ ]:
merged_df.loc[
    merged_df["product_category_name"].isna(),
    "price"
].sum()

In [9]:
merged_df['review_comment_title'].fillna('No Comments', inplace=True)

C:\Users\mohammedjav-67239\AppData\Local\Temp\ipykernel_129664\1711205788.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['review_comment_title'].fillna('No Comments', inplace=True)

In [10]:
merged_df['review_comment_message'].fillna('No Comments', inplace=True)

C:\Users\mohammedjav-67239\AppData\Local\Temp\ipykernel_129664\1317794511.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['review_comment_message'].fillna('No Comments', inplace=True)

In [48]:
# merged_df.columns
merged_df.isna().sum()
# merged_df["product_category_name"].isna()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date     1235
order_delivered_customer_date    2471
order_estimated_delivery_date       0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
payment_sequential                  0
payment_type                        0
payment_installments                0
payment_value                       0
review_id                           0
review_score                        0
review_comment_title                0
review_comment_message              0
review_creation_date                0
review_answer_timestamp             0
product_category_name            1143
product_name_lenght              1695
product_description_lenght       1695
product_photos_qty               1695
product_weight_g                   20
product_length_cm                  20
product_height_cm                  20
product_width_cm                   20
seller_zip_code_prefix              0
seller_city                         0
seller_state                        0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
geolocation_zip_code_prefix       316
geolocation_lat                   316
geolocation_lng                   316
dtype: int64

In [46]:
# merged_df.loc[merged_df["product_category_name"].isna(), "seller_id_x"].value_counts()
# merged_df["product_category_name"].isna().sum()
# merged_df.loc[
#     (merged_df["seller_id"] == "1ca7077d890b907f89be8c954a02686a") &
#     (merged_df["product_category_name"].notna()),
#     "product_category_name"
# ].value_counts()
merged_df.loc[(merged_df["seller_id"] == "1ca7077d890b907f89be8c954a02686a") & (merged_df["product_category_name"].isna()), "product_category_name"] = "telefonia"

In [47]:
merged_df.loc[
    merged_df["product_category_name"].isna(),
    "seller_id"
].value_counts()

seller_id
46dc3b2cc0980fb8ec44634e21d2718e    39
004c9cd9d87a3c30c522c48c4fc07416    39
0c8380b62e38e8a1e6adbeba7eb9688c    32
fc906263ca5083d09dce42fe02247800    30
520b493b57809f446cb0a233bb3e25c7    25
                                    ..
75fdd0a732287f9497b179f6bd445d32     1
3db66a856d18a9cba7c9241fc5221c50     1
fe1bbc5feda5c8979a8a1b3b2512d5a6     1
749e7cdabbaf72f16677859e27874ba5     1
9ef932e837d8b7f392c0bfee9d359dc2     1
Name: count, Length: 251, dtype: int64

In [11]:
merged_df.to_csv(
    "files/cleaned/olist_final_dataset.csv",
    index=False
)

In [2]:
import pandas as pd
merged_df = pd.read_csv("files/cleaned/olist_final_dataset.csv")

In [51]:
merged_df.drop_duplicates()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,seller_zip_code_prefix,seller_city,seller_state,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,9350,maua,SP,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,3149.0,-23.576983,-46.587161
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,9350,maua,SP,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,3149.0,-23.576983,-46.587161
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,9350,maua,SP,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,3149.0,-23.576983,-46.587161
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,...,31570,belo horizonte,SP,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,47813.0,-12.177924,-44.660711
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,aa4383b373c6aca5d8797843e5594415,...,14840,guariba,SP,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,75265.0,-16.745150,-48.514783
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117324,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,17602,tupa,SP,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,11722.0,-24.001500,-46.449864
117325,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1,b80910977a37536adeddd63663f916ad,...,8290,sao paulo,SP,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA,45920.0,-17.898358,-39.373630
117326,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,1,d1c427060a0f73f6b889a5c7c61f2ac4,...,37175,ilicinea,MG,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,28685.0,-22.562825,-42.694574
117327,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2,d1c427060a0f73f6b889a5c7c61f2ac4,...,37175,ilicinea,MG,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,28685.0,-22.562825,-42.694574
117328,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1,006619bbed68b000c8ba3f8725d5409e,...,14407,franca,SP,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,83750.0,-25.764308,-49.720376

In [54]:
merged_df = merged_df.dropna(
    subset=["order_approved_at"])

In [71]:
# merged_df.loc[
#     merged_df["order_delivered_carrier_date"].isna(),
#     "order_status"
# ].value_counts() // getting 3 record for delivered
merged_df.loc[(merged_df["order_delivered_carrier_date"].isna()) & (merged_df["order_status"] == 'delivered')]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,seller_zip_code_prefix,seller_city,seller_state,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng
86260,2aa91108853cecb43c84a5dc5b277475,afeb16c7f46396c0ed54acb45ccaaa40,delivered,2017-09-29 08:52:58,2017-09-29 09:07:16,NaN,2017-11-20 19:44:47,2017-11-14 00:00:00,1,44c2baf621113fa7ac95fa06b4afbc68,...,87240,terra boa,PR,a2ac81ecc3704410ae240e74d4f0af40,13334,indaiatuba,SP,13334.0,-23.082208,-47.203433
109258,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00,1,30b5b5635a79548a48d04162d971848f,...,5319,sao paulo,SP,d77cf4be2654aa70ef150f8bfec076a6,91330,porto alegre,RS,91330.0,-30.033566,-51.162560

In [72]:
merged_df.shape

(117314, 42)

In [8]:
condition = (
    (merged_df["order_status"] == "delivered") &
    (merged_df["order_delivered_carrier_date"].isna())
)

# condition = (
#     (merged_df["order_status"] == "delivered") &
#     (merged_df["order_delivered_customer_date"].isna())
# )

merged_df = merged_df.loc[~condition]

In [23]:
# merged_df.isna().sum()
merged_df.loc[
    merged_df["geolocation_zip_code_prefix"].isna(),
    "customer_zip_code_prefix"
].value_counts()

customer_zip_code_prefix
70686    18
72005    14
71919    10
61906     8
72300     7
         ..
35408     1
87511     1
57254     1
72237     1
56327     1
Name: count, Length: 155, dtype: int64