In [42]:
import pandas as pd

# pd.read_csv("data.tsv.txt", sep="\t")
details = pd.read_table("data.tsv.txt")
print(details.head())

   order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa
1         1         1                                   Izze
2         1         1                       Nantucket Nectar
3         1         1  Chips and Tomatillo-Green Chili Salsa
4         2         2                           Chicken Bowl

                                  choice_description item_price
0                                                NaN     $2.39
1                                       [Clementine]     $3.39
2                                            [Apple]     $3.39
3                                                NaN     $2.39
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

FOR Attributes no nooed to put ()
function has ()

Terminology Alert  
Rows - Observations/Record  
Columns - Features/Parameter

In [43]:
details.shape

(4622, 5)

In [44]:
details.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [45]:
details.describe(include="all")

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

4.2  Find out item sold in restaurent

In [46]:
details.nunique()

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [47]:
print(details['item_name'].unique())

['Chips and Fresh Tomato Salsa' 'Izze' 'Nantucket Nectar'
 'Chips and Tomatillo-Green Chili Salsa' 'Chicken Bowl' 'Side of Chips'
 'Steak Burrito' 'Steak Soft Tacos' 'Chips and Guacamole'
 'Chicken Crispy Tacos' 'Chicken Soft Tacos' 'Chicken Burrito'
 'Canned Soda' 'Barbacoa Burrito' 'Carnitas Burrito' 'Carnitas Bowl'
 'Bottled Water' 'Chips and Tomatillo Green Chili Salsa' 'Barbacoa Bowl'
 'Chips' 'Chicken Salad Bowl' 'Steak Bowl' 'Barbacoa Soft Tacos'
 'Veggie Burrito' 'Veggie Bowl' 'Steak Crispy Tacos'
 'Chips and Tomatillo Red Chili Salsa' 'Barbacoa Crispy Tacos'
 'Veggie Salad Bowl' 'Chips and Roasted Chili-Corn Salsa'
 'Chips and Roasted Chili Corn Salsa' 'Carnitas Soft Tacos'
 'Chicken Salad' 'Canned Soft Drink' 'Steak Salad Bowl'
 '6 Pack Soft Drink' 'Chips and Tomatillo-Red Chili Salsa' 'Bowl'
 'Burrito' 'Crispy Tacos' 'Carnitas Crispy Tacos' 'Steak Salad'
 'Chips and Mild Fresh Tomato Salsa' 'Veggie Soft Tacos'
 'Carnitas Salad Bowl' 'Barbacoa Salad Bowl' 'Salad' 'Veggie Crispy Tacos'
 'Veggie Salad' 'Carnitas Salad']

4.3 top 5 selling items

In [48]:
details.groupby("item_name")['quantity'].sum().sort_values(ascending=False).head()

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

4.4 Least 5 selling item

In [49]:
details.groupby("item_name")["quantity"].sum().sort_values().head()

item_name
Carnitas Salad                       1
Veggie Crispy Tacos                  1
Chips and Mild Fresh Tomato Salsa    1
Crispy Tacos                         2
Salad                                2
Name: quantity, dtype: int64

DATA CLEANING

In [50]:
details['item_price'] = details['item_price'].str.replace('$', '').astype(float)

In [51]:
details.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

TASK  
1) Top 5 selling item with renevue it made  
2) total revenue of top 5 item  
3) FInd out 2 more question of same dataset

In [52]:
details.groupby("item_name")['item_price'].sum().sort_values(ascending=False).head()

item_name
Chicken Bowl           7342.73
Chicken Burrito        5575.82
Steak Burrito          3851.43
Steak Bowl             2260.19
Chips and Guacamole    2201.04
Name: item_price, dtype: float64

In [53]:
details.assign(revenue=details["quantity"] * details["item_price"]).groupby("item_name")["revenue"].sum().sort_values(ascending=False).head(5)

item_name
Chicken Bowl           8044.63
Chicken Burrito        6387.06
Steak Burrito          4236.13
Steak Bowl             2479.81
Chips and Guacamole    2475.62
Name: revenue, dtype: float64

Chapter 3 - Pandas Data Structure  
1D - Series  
2D - DataFrames

In [54]:
pd.Series(data=[1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'], name='my_series')

a    1
b    2
c    3
d    4
e    5
Name: my_series, dtype: int64

In [57]:
pd.DataFrame(data= {"name":["ram", "jam", "sam"], "english":[90, 55, 60], "science":[55, 74, 100]})

  name  english  science
0  ram       90       55
1  jam       55       74
2  sam       60      100

Chapter 4 - filtering & selecting & sorting

Chapter 5 - Missing Values

Step 1 - Check with client and ask wheather they can provide proper data   

if not   
step 2 - remove duplicate data   
step 3 - find out null values  
step 4 - drop null records

In [60]:
data = pd.read_csv("data.tsv.txt", sep = '\t')

In [65]:
data.duplicated().sum()

0

In [64]:
data.drop_duplicates(inplace=True)

In [ ]:
data.isnull().sum()
df.dropna() # remove if atleast one column has null

order_id                 0
quantity                 0
item_name                0
choice_description    1228
item_price               0
dtype: int64